spring:
  datasource:
    url: jdbc:mysql://localhost:3306/douyin
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    #    开发关闭缓存 以观察实时效果
    cache: false
  servlet:
    multipart:
      max-file-size: 50MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true